# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				axolotl = true
				arrow = true
				cow = true
				tropical_fish = true
				fox = true
				pig = true
				slime = true
				pillager = true
				skeleton = true
				bat = true
				area_effect_cloud = true
				rabbit = true
				zombie = true
				armor_stand = true
				drowned = true
				sheep = true
				experience_orb = true
				player = true
				item = true
				wolf = true
				salmon = true
				zombie_villager = true
				goat = true
				boat = true
				item_frame = true
				painting = true
				glow_squid = true
				witch = true
				glow_item_frame = false
				squid = true
				spider = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.bclib]
				chair = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				iceologer = true

			[light_sources.settings.entities.creeperoverhaul]
				snowy_creeper = true
				dripstone_creeper = true
				cave_creeper = true
				spruce_creeper = true

			[light_sources.settings.entities.tinyskeletons]
				baby_skeleton = true

